name: Test

on:
    workflow_dispatch:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install stable Rust toolchain
              run: rustup toolchain install stable --profile minimal

            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2

            - name: Check
              run: cargo check

            - name: Build
              run: cargo build --verbose

            - name: Test
              run: cargo test --verbose

